### ISSUE TITLE
need flags and map images on strapi for plan with us

### ISSUE THREAD

**Issue by bibekshhh** [Himalayan-Adventure/frontend#76]
![WhatsApp Image 2024-12-14 at 21 14 40_6027cdda](https://github.com/user-attachments/assets/7fd2eb3b-2216-40a7-baea-b54490a055fb)

**Comment by SajjanKarn** [comment]
@bini2002 check this section in postman for dynamic flags and countries
![image](https://github.com/user-attachments/assets/a9362d08-efd1-496c-821a-f613b1a95b91)
